version: 1.0.{build}
image: Visual Studio 2019
before_build:
- cmd: |-
    cd C:\projects\caesar
    cmake --version
    cmake .. -G %generator% c:\projects\caesar
build:
  project: c:\projects\caesar\caesar.sln
  verbosity: minimal
  parallel: true
only_commits:
  files:
    - CMakeLists.txt
    - appveyor.yml
    - source/
    - cmake/
artifacts:
- path: Release\caesar.exe
- path: Debug\caesar.exe
