version: 1.0.{build}
image: Visual Studio 2019
before_build:
- cmd: >-
    cmake --version

    cmake .. -G %generator% c:\projects\caesar
build:
  verbosity: minimal
artifacts:
- path: Release\caesar.exe
- path: Debug\caesar.exe